### PR TITLE
Hide the actual process name to bypass Valve Anti-Cheat check

### PR DESCRIPTION
**Pull request by Alias95**
this change will give unique process name on each run . so you make sure that Valve Anti-Cheat can't give you ban in case they found ProjectX running in your machine while the game is ON 

image

### CODE REVIEW

**Comment by XanOpiat** [comment]
I dont think theres really any point in doing this, as vac doesnt use the actual process name to detect cheats

**Comment by XanOpiat** [comment]
If you have any further info on why this would be helpful please tell me

**Comment by Alias95** [comment]
well , that not true . not sure if you ever heard about 2020 ban wave . 
https://www.talkesport.com/news/csgo-vac-wave-wipes-cheaters-with-new-detections/
you can check ⬆️ 

The real story of that cheat application was that the developers started saving come temp data under specific directory in
 **C:** Disk   with specific unique name .
then new release came to csgo and they started reading that directory. and if you are cheating or not ( if that file exists on your pc , you will get banned ) . 
I know people who got banned on their real account ( without running the cheat not even once on that account) 

just because they use it on their secondary one and the file stored there . 

anyway it's your choice ,  maybe they are not reading it for now but what happen before prove that  they might do a release just for specific thing and that gonna be very easy for them to detect if they decided to list all the process and check for ProjectX 😅

**Comment by XanOpiat** [comment]
I know about this banwave but how do you know about the stuff with the specific file?
I mean this basically goes against most of the stuff we know about vac right?
Because you cannot get banned for just having programs on your pc if they are not actively interacting with csgo.
https://www.unknowncheats.me/forum/anti-cheat-bypass/100197-vac-external-tool-detection-and-more.html?subid1=20220105-0013-4535-a8b9-ff3a4cc513bd
https://guidedhacking.com/threads/how-to-bypass-vac-valve-anti-cheat-info.8125/
For example you wont even be banned if you use cheat engine with another process while csgo is running.
Changing the name of a process wont really do anything as they are instead checking for certian signatures in the hash of the file.

**Comment by XanOpiat** [comment]
Thanks for the input tho 👍

**Pull request closed without merging**
